### ISSUE TITLE
Intergrate into heishamon release

### ISSUE THREAD

**Issue by IgorYbema** [salakrzy/HeishaMonBoth#5]
Hi,
Thank you for the great work! The idea of chaining the CZ-TAW1 through heishamon is something which was thought before earlier but never implemented due to lack of GPIO's. Never had time to change the code to an ESP32 style but you have done this already. Great!

I hope you don't mind that I'll take your changes into a future release of heishamon and a redesign of the pcb to add the connector.

**Comment by Misiu** [comment]
@IgorYbema any updates on this?
Also, do you plan to do PR to https://github.com/Egyras/HeishaMon or in your fork?
I just got my heat pump installed and I would like to add it to Home Assistant, so I wondering if should I wait for a new PCB or order the old one.

**Comment by KickStomp** [comment]
Hello, I would also love to use the "HeishaMonBoth", are there any plans to create a PCB which then could be bought?
;-)

**Comment by salakrzy** [comment]
Hello, 
I'm glad you like the idea. Of course anyone who wants can use, copy and publish the result of my work on this interface. Thank you for every star clicked for this project;-)

I have a few HeishaMonBoth interface PCBs.  If you are interested in shipping, please send an email to [pompadom@wp.pl] 
The assembled interface looks like in the attached pictures.

![Board Top1](https://github.com/salakrzy/HeishaMonBoth/assets/23367030/8ce96b7c-1fc0-448e-a932-dc4bd741cd9c)
![Kabel do CZTAW1](https://github.com/salakrzy/HeishaMonBoth/assets/23367030/d420f917-d12a-4eb2-be9b-9e3e350e7562)

**Comment by salakrzy** [comment]
![Board bottom](https://github.com/salakrzy/HeishaMonBoth/assets/23367030/f7d85baa-ff3a-4efb-9534-714915b2dcf6)

**Comment by IgorYbema** [comment]
Hi,
I have made a modified heishamon with this and ordered some test boards. Hopefully they work and I can use your code on them and start integrating your changes into the main project. One question, did you run into any problems with the CZTAW connected to your board and both being powered from the heatpump?

![image](https://github.com/salakrzy/HeishaMonBoth/assets/20365971/d3c8ffb4-0eac-47eb-906f-f7353154ad6a)

**Comment by salakrzy** [comment]
Your PCB looks cool. I did not observe any problems with the simultaneous power supply of the board and CZTAW1. You can always reduce the WiFi power. Some ideas on how to reduce the power consumption of the ESP32 are described here.  [https://mischianti.org/esp32-practical-power-saving-manage-wifi-and-cpu-1/](url)
