### ISSUE TITLE
MD5 NOT Matched

### ISSUE THREAD

**Issue by emjotpe** [salakrzy/HeishaMonBoth#8]
In Windows PowerShell:
certutil -hashfile UART_HMBoth_v3_2_3.bin MD5
MD5 hash of UART_HMBoth_v3_2_3.bin:
9124d9d4fe943c6bd0320e4bdc46f50e
CertUtil: -hashfile command completed successfully.

**Comment by salakrzy** [comment]
thx. now both UARTxxx.bin and OTAxxx.bin  MD5 should be corect.
